twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        date_format: '%app.date_format%'
        category_repository: '@App\Repository\CategoryRepository'
when@test:
    twig:
        strict_variables: true
